import { chromium } from 'playwright'
const OUT='/tmp/claude-0/-home-user-reflect/d04526bc-7ea2-5503-963c-a1919345c2de/scratchpad/g'
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium', args:['--enable-unsafe-swiftshader','--use-angle=swiftshader','--disable-gpu-sandbox'] })
const p = await b.newPage({ viewport:{width:1440,height:900} })
const errs=[]; p.on('pageerror',e=>errs.push(String(e).slice(0,220)))
await p.goto('http://127.0.0.1:4173/')
await p.waitForTimeout(500)
await p.screenshot({path:`${OUT}/dbg-1-load.png`})
const hasBtn = await p.getByText('LOAD SAMPLE').count()
await p.getByText('LOAD SAMPLE').click({timeout:5000}).catch(e=>errs.push('click:'+e.message.slice(0,80)))
await p.waitForTimeout(2500)
await p.screenshot({path:`${OUT}/dbg-2-after.png`})
const emptyVisible = await p.locator('.empty').isVisible().catch(()=>null)
console.log(JSON.stringify({hasBtn, emptyVisible, errs}))
await b.close()
