import { chromium } from 'playwright'
const OUT='/tmp/claude-0/-home-user-reflect/d04526bc-7ea2-5503-963c-a1919345c2de/scratchpad/g'
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium', args:['--enable-unsafe-swiftshader','--use-angle=swiftshader','--disable-gpu-sandbox'] })
const p = await b.newPage({ viewport:{width:390,height:844}, isMobile:true, hasTouch:true })
const errs=[]; p.on('pageerror',e=>errs.push(String(e).slice(0,180)))
await p.goto('http://127.0.0.1:4173/')
await p.waitForTimeout(600)
await p.screenshot({path:`${OUT}/mob-empty.png`, fullPage:true})
const box = await p.getByText('LOAD SAMPLE').boundingBox().catch(()=>null)
const topbarBox = await p.locator('.topbar').boundingBox().catch(()=>null)
const stageBox = await p.locator('.stage').boundingBox().catch(()=>null)
console.log('LOADSAMPLE box', JSON.stringify(box))
console.log('topbar', JSON.stringify(topbarBox))
console.log('stage', JSON.stringify(stageBox))
console.log('errs', JSON.stringify(errs))
await b.close()
